homepage:
    path:       /
    controller: App\Controller\MenuControllers\MyProfileController::HomePage
login:
    path:       /login
    controller: App\Controller\SecurityController::login
test:
    path:       /mainMenu
    controller: App\Controller\TestingController::redirectToNotCreatedYetRoute
app_logout:
    path: /
registration:
    path:       /register
    controller: App\Controller\RegistrationController::register
forgot_password:
    path:       /forgot_password
    controller: App\Controller\SecurityController::forgotPassword
creating_post:
    path:       /create_new_post/blogger
    controller: App\Controller\MenuControllers\CreatePostController::createPost
all_posts:
    path:       /view_all_posts/profile
    controller: App\Controller\MenuControllers\AllPostsController::viewAllPosts
edit_profile:
    path:       /edit_profile/profile
    controller: App\Controller\MenuControllers\MyProfileController::editProfile
view_my_posts:
    path:       /view_my_posts/blogger
    controller: App\Controller\MenuControllers\MyProfileController::viewMyPosts

admin_page:
    path:       /admin_page/admin
    controller: App\Controller\AdminController
i_want_to_be_a_blogger_notice:
    path:       /view_notice/moderator
    controller: App\Controller\ModeratorController::viewNotice
view_specific_user_home_page:
    path:       /view_specific_home_page/{id}
    controller: App\Controller\MenuControllers\ViewSpecificUserPageController::prepareToViewSpecificUsersHomePage
user_post:
    path:       /user_post
    controller: App\Controller\PostController::userPost
post_show:
    path:       /post_show
    controller: App\Controller\PostController::show
wrong_email:
    path:       /wrong_email
    controller: App\Controller\RegistrationController::wrongEmail
view_my_post:
    path:       /view_specific_home_page
    controller: App\Controller\MenuControllers\ViewSpecificUserPageController::myPosts
view_my_profile:
    path:       /view_profile
    controller: App\Controller\MenuControllers\ViewSpecificUserPageController::myProfile

