#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path:       /login
    controller: App\Controller\SecurityController::login
   # path:       /login2
    #controller: App\Controller\SecurityController2::login
test:
    path:       /test
    controller: App\Controller\TestingController::redirectToNotCreatedYetRoute
app_logout:
    path: /logout
registration:
    path:       /register
    controller: App\Controller\RegistrationController::register
forgot_password:
    path:       /forgot_password
    controller: App\Controller\SecurityController::forgotPassword
creating_post:
    path:       /create_new_post/blogger
    controller: App\Controller\MenuControllers\CreatePostController::createPost
all_posts:
    path:       /view_all_posts/profile
    controller: App\Controller\MenuControllers\AllPostsController::viewAllPosts
edit_profile:
    path:       /edit_profile/profile
    controller: App\Controller\MenuControllers\MyProfileController::editProfile
view_my_posts:
    path:       /view_my_posts/blogger
    controller: App\Controller\MenuControllers\MyProfileController::viewMyPosts

