#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path:       /login
    controller: App\Controller\SecurityController::login
test:
    path:       /test
    controller: App\Controller\TestingController::redirectToNotCreatedYetRoute
app_logout:
    path: /logout
registration:
    path:       /register
    controller: App\Controller\RegistrationController::register
